# Generated by Django 4.2.5 on 2023-09-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("concertconnect", "0002_alter_tier_price_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_status",
            field=models.CharField(
                choices=[("PENDING", "PENDING"), ("COMPLETED", "COMPLETED")],
                default="PENDING",
                max_length=15,
            ),
        ),
    ]
